### ISSUE TITLE
Cloud scope locks to major current version, not version of cloud

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/docs#175] opened 2022-10-31 13:52 UTC
Teleport Cloud is not always the same version as the current released version.  If a user selects the Cloud scope they are automatically set to the current major version.  That can lead to issues of incompatible instructions where the user is using the next major version steps on 

Example: 

Teleport Cloud on V10.  User selects V10 and Cloud.  Docs will then fix the user to V11 scope.  In the case of V11 there is a new `proxy_server` field in the Teleport config that is not supported in v10.

**Comment by ptgott** [comment] 2023-08-02 21:19
Closing as a duplicate of https://github.com/gravitational/docs/issues/302. Closing this one since #302 has more discussion.

**Closed by ptgott** 2023-08-02 21:19 UTC
